version: "2.1"
services:
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Moscow
      # - TRANSMISSION_WEB_HOME= #optional
      - USER=${USER} #optional
      - PASS=${PASS} #optional
      # - WHITELIST=iplist #optional
      # - PEERPORT=peerport #optional
      # - "HOST_WHITELIST=dnsname list" #optional
    volumes:
      - transmission:/config
      - transmission_nfs:/Downloads
      - transmission:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.transmission.rule=Host(`transmission.hogin.pro`)"
      - "traefik.http.routers.transmission.entrypoints=websecure"
      - "traefik.http.services.transmission.loadbalancer.server.port=9091"
      - "traefik.http.routers.transmission.tls.certresolver=myresolver"
      # - "traefik.http.routers.transmission.middlewares=authentik@docker"
      # - "docker-volume-backup.stop-during-backup=stopservice"
      - "com.centurylinklabs.watchtower.enable=true"
    deploy:
      resources:
        limits:
          cpus: "8"
          memory: 16G
    networks:
      - transmission
      # - ip6net
volumes:
  transmission:
    name: transmission
    
  transmission_nfs:
    name: transmission_nfs
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=fs01.msk.hogin.pro,rw"
      device: ":/mnt/home/share-folder/Downloads"

networks:
  transmission:
    name: transmission
  # ip6net:
  #   name: ip6net