version: "2.1"
services:
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Moscow
      # - TRANSMISSION_WEB_HOME= #optional
      - USER=${USER} #optional
      - PASS=${PASS} #optional
      # - WHITELIST=iplist #optional
      # - PEERPORT=peerport #optional
      # - "HOST_WHITELIST=dnsname list" #optional
    volumes:
      - transmission:/config
      - /mnt/Media/Downloads:/Downloads
      - transmission:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.transmission.rule=Host(`transmission.ypstudio.ru`)"
      - "traefik.http.routers.transmission.entrypoints=websecure"
      - "traefik.http.services.transmission.loadbalancer.server.port=9091"
      - "traefik.http.routers.transmission.tls.certresolver=myresolver"
      - "docker-volume-backup.stop-during-backup=stopservice"
    networks:
      - traefik
volumes:
  transmission:
    name: transmission_transmission
networks:
  traefik:
    name: traefik